---

- hosts: all
  remote_user: vagrant

  roles:

    - apache-server
    - djangocms-app
    - djangocms-app_init

  post_tasks:

    - command: echo 'Good to go!'
      notify:
        - Restart Server