---

- stat: path={{ backend }}/manage.py
  register: project

- stat: path={{ backend }}/requirements.txt
  register: project_requirements

- name: A project will exist.
  shell: . {{ backend_env }}/bin/activate && djangocms -p . project -s
            --django-version=stable
            --cms-version=stable
            --i18n=yes
            --languages=en
            --use-tz=yes
            --db=sqlite:///{{ backend }}/project.db
            --permissions=yes
            --reversion=yes
            --bootstrap=no
            --starting-page=no
            --no-input chdir={{ backend }}
  when: project.stat.exists is not defined or project.stat.exists == False

- name: A project requirements file will exist.
  shell: . {{ backend_env}}/bin/activate && pip freeze > requirements.txt chdir={{ backend }}
  when: project_requirements.stat.exists is not defined or project_requirements.stat.exists == False

- name: Project requirements will be installed.
  pip: requirements={{ backend }}/requirements.txt virtualenv={{ backend_env }}

- name: Project schema will be applied to the database engine.
  shell: . {{ backend_env }}/bin/activate && python manage.py migrate chdir={{ backend }}

- name: Project static files will be collected.
  shell: . {{ backend_env }}/bin/activate && python manage.py collectstatic --noinput chdir={{ backend }}
